# Generated by Django 4.0.5 on 2022-06-09 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_type', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_brand', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_capacity', models.FloatField()),
                ('model', models.CharField(blank=True, default='', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=20)),
                ('year', models.IntegerField(blank=True, max_length=4)),
                ('enrollment_year', models.IntegerField(blank=True, max_length=4)),
                ('color', models.CharField(blank=True, default='sin color', max_length=20)),
                ('licence_plate', models.CharField(max_length=10)),
                ('serial_engine', models.CharField(max_length=100)),
                ('serial_chasis', models.CharField(max_length=100)),
                ('bike_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.biketype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.brands')),
            ],
        ),
    ]
