# Generated by Django 4.0.5 on 2022-06-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='enrollment_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
